apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rucio-root-account
  namespace: rucio-dev
spec:
  encryptedData:
    root-password: AgCQmTBh6z7laOxaEpEhMePLWsI9NYXne11tg1BPVj7yufpT5vavJ6NwHyaIwcAQX5JrmAAuWj4dmRwT1nJ86/DXCaDIUJDcmuVKW2pAz9IpK47b9M4VUXKe51HBw8W4e4LD4IqKoFjxLEHSB3QoY+RGun6X9VVp5zhzD/4KYg4jg2Y2cshJiLQNkQH4FGHuRxXIT5vwj4my5t5bUnN3zOtebG/TjQM5IeI+xUwQnU9cc2gGlpQ5tt2jEQRrqDreOOEMUGaYAtCqg9WHaDrT6JuJw8ewEpMRINLOQbVGEnI1SPholG49RabhlGXvkUbUCPmNBG1r91ia2Uqejf7VIimJRgVf0hQyEA8WxdwH0v/71jyZnqJyxHBwLVdCVcu/IHnv3JW1R/c0T2Fg3WktyBq8E7fiUQ3wt8A6XTg82rAsCvoLYHt3+fNao+rUFR22OOYbTDT20DHDk2W00aIAuSzJtbWv5XlJktdmq3TEc9Vdpuo/pZk/O10vmLK32SXZr/E322fmjJc+dN+s4ywKSidj7U4Ut9BaQyb7KdAtxmgbSz41kTG+ye7tsUFxYwWeNSsulPXXkLXfGDal7j+X3Wb7q5NLmDWIb1GupcVAFoZajhV4lJqDQzo6lHZZ6ig/8/vaqNwQN+IOw8eqRIOgQoOE+f/LOGcqPidaZCoOLtugZKbw4ZY9qNZvmozQiaz62BKpBIQk5pg=
    root-username: AgDKfyagRSl7LcwCfG20me4gHKcDzaN+pbbDcthfU0hYCX2Db8Rfzbb+b/TjfpBjQiRndQAhACPYv72iclZael7tZmelc3rPDrhSMtgUH7jQm6rMp3pp80P4vr6FhZkGKQkVq2QE+xJRe9jPvdKiCS2CDuMZMu9JaVQNqsNuQkgj+DY96Kd/XUcnYF7EN8yayq8Yus/DLY4Aa9nJbcxHBt6LfiJngYe0AgPlAvSEsl2nlgFXH9sBr9DmMSe4U0tXJGiJHHTjkLzjXGq9F0EPB0tRESMtADhNPdV3ZafZEQkP5LzVmjnHQdypy5guDtSKtoCllT45feLDzKnyoB/qMvHUpA0H81UbLeWaBf0A6BLiy6b/Aa0Y0oFkr0kkAf0qAQcAo+nJfRwHsMsS4/vPoZ8MfLcG5DXGXbWkMwquovE19d9aRydCRs/VoYfV+2lq3g5/OfPXlAaOeDLKsrGLnaQzXqB+1qYLQoUqQIurQuCQqted5mO337Fz9wwMXD8Zta5HIvGfPI340lLXRgZKFbqy8lISIDQBZY1prSlimygsOGxI2APV6Vsf9sJrC3aDG1sogSwUGHE1TJnAu4ciCzsSg47yak6CcQXYDxqWmX0ELfdRjhmo2+S200EXyrJAd0JXvf7mYaOOLymJUJWGte2guLCp6rXoHNXJXTRroGlpryAP3izY5Qan6+2mcyN6Dhwc6Bk1c8I=
  template:
    metadata:
      creationTimestamp: null
      name: rucio-root-account
      namespace: rucio-dev

