apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: servers-dev-rse-accounts
  namespace: rucio-dev
spec:
  encryptedData:
    rse-accounts.cfg: AgDNzKQZHPWYJGDbRRz/TAVH3FFm12BOlzje3hEzLm/nN5UKvO3N3jn++roURTYWpuju9I58B4RwgAkKUPLXtsZ+rFeVuy6+fsQYJpqP96xMLkruAteahGPKI7PuxnYc+D290q1AKVbafWgv/kjJKeEO8FwUFYiOKruVFdLeu36j68FW4QloUvfPwS93VHz1MZQbzT3b/X3oTGx0lmxAPa7BVHGpT7THD2CeGIWHDUNhcemzOY/4zjen+9aozuH6pdGjriXLqqapoZWmrjeWFvRjZgKl9M/lYztfQ8E1vtGA0I4dW1INAyDPXb3lpNrdbNo2WfCsBgsyMeIp7OTNQShoG/+sezLokTHvdM3aOnUZTcdoWk5PWnViEdBa8eO+gusZ+mAArQWbDLiN4CGIv1T0VwjRTVC9P9ifNFkqs/8LA434Y5i/zkbeAw0Q8HIy2UWfMrgaRGefDrqpFMT1u4obrinDm00mo7VTpYcLJA9UpdR+DNB5bujOPM3Q8xpb3QONbbHxLmuOn5CNvCivj73IJyB6wVUiuz6saSCMuovr2y5xyU7zXVWUhJKOUCwc7gtveYmzBAn2JebDqx4w1c8XwQaUpoSVYdYds9KnERmfJHy7/UdPJZe0LsCwNEbcevkLEhz5UP+m4cnID/FOcHhTeTtSymNdTlUXxJNWu7/B+5R5LzIXGuYbASy1ybADxir4H7s3/yFM5PYI26juFS9eu6aCvJLXneGF4X4Ek4kbuy6NJLqqpdiSqzr4hDhS1UXbZ1rDrufCOxGHd4BNvGqm2fCcv6hjvX857w5v+Hw/mPXqD408B+NZvpvurCZ8HTtVeH7fOTz53eYBrR9Y4Tp/IgyD2vj96+hbqNuHymni1vpWymYLbzhTTi4oVcWl7J3BlCI9yANC2C5nZxX+8Ds/J5qSwhpT0vm76nRv8iRKtkKCMjPPqUGXS9IbLMk4ghPha05uwpjArfrjomF8nleYphJLoJOLIBMVUmUc245fhrErCzP4DceAme5g7Lh3dPZir3vpENiqrG33qO9fz56tsw==
  template:
    metadata:
      creationTimestamp: null
      name: servers-dev-rse-accounts
      namespace: rucio-dev

