apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webui-dev-hostkey
  namespace: rucio-dev
spec:
  encryptedData:
    hostkey.pem: AgDLiJn7PQ+b6weqKCZbMXQfup5ENfzGiBcw0mzetNBLU+UlUz703Tz2ZdYWxuOHIOoaHAaQ7w+0lIQkbogeyRtJlbxu6jD37cW52Q1AMP6eajutlMTnYc7GYRVAZObNU1dL44Okh6qcXhAcCtlAPu0jcHGn5ud1OOIuMxW/jg51iGcpGF+efdWWD6Iiasu3rEOMiaQZiXTRIqCH+JPjrfUi0HQIZDHoctSrpysc1M0YQDNsPZebaE3B0glXfHM5sEmrxem0bznCqahHMbCoWE+qhdpoo0yUZEl8jU7jORz7pxXhOfj8h+nLd+Cx8ThhDONCxuGxiYUpush7C6GBcFvctwThE+jS94kgwhP/LhGfxdL9CxSWZ2VqbA1D+Qa3u8hiSrHRzoq/BHbDeoKqDTIAWVR7MEsKgYkKmNF/Q7cavvmh6bT+lDoe+D7hK/iQ1gaR1SYMuq3xw/4Db+jCKUlt44kBCvJ4p7a1n8+XGClPfgWy6rD+SWjNyQdw4+acJNyy2mEjY6t2NJKCjwilbb4RnOkgwxeZg8njMsaTRT6lcpNXHF806FvU8l5Iw5zPR5FKUVVAMQ3WWmgXjVnHbekLDTB22JR8yb3jxB4jS1ULOpBp/eJvyF8qR8IPYxn7KJA701wvRsfIeKeyx7iZ0Vi6TRG8gOejbVecQSDeVgf5u37+obNOS3WOYHTHQkQK+x2JDD5aylMShC+h2GDi5HrsHul7
  template:
    metadata:
      creationTimestamp: null
      name: webui-dev-hostkey
      namespace: rucio-dev

