apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webui-dev-hostcert
  namespace: rucio-dev
spec:
  encryptedData:
    hostcert.pem: AgA6wt98eDiymb293Dw4eb9Xb0Db859yUWCow2QAwZGBRX+EaGfVSmzTv0YUw8vpq+vGpTdQBTTfD+U3d/Ic6DL/4VJUDVLEDViXX7iQYR/rFwOlr1pFaIjgjAaO82UmB55tLzuHhuxnHI7omq9DjGQbff5mhNVVbDhM1Qcu2KeUQFwIl7iXkCcsLw01/uFXFUsKuLa5nM8VMToyRljbUOiGiMv9KUWt3S2WQ4BLF+Br9nJYezdddHPiaEd1vl8IwjPjWfPt+2MjCMrfCKcgFIOdURvgMQ5Jfz02PLcf7oEiGaJcAC/KCAGbgJETnKUFJgIsdFIW5jpjJBN1+3sdoslxtO00WzA9+gE4L0730UeOafB3l2wuDHdXKm2XLV2P8dyHp1Zx6KBD2u/6zV3XtjisCDnhvJfrb0UV9C1cigqxc8nxeyYcmETFdc6yhXK6fBLlWCKKEziBfoz7e1Vhc7ntrAwFkGs/73KBi7jMf/dhQ9HbfA9pSAIBLJNo9Fc7kj+HkIpQiVjO1jfo0fZh5XpMb6Q9d06V1ZBXKCe3tQB/vXF3j2u5ffBjkuXdMlb5t347o0KwL3xmHUGoi1bg57H1GDTcASncJx9zhVcHvOx1QzUYpXdbgh/KLa3g/swVn6MU6HM+HUPLZnU1MEKxrib/K1I4GuKwMUVb1uiEI69k7Jnza4t5sVMVGZizrAk7+V4=
  template:
    metadata:
      creationTimestamp: null
      name: webui-dev-hostcert
      namespace: rucio-dev

