
# Based on docs and snippets from https://github.com/cvmfs-contrib/cvmfs-csi

# Create StorageClass for provisioning CVMFS automount volumes,
# and a PersistentVolumeClaim that's fulfilled by the StorageClass.

# If Controller plugin is not deployed, follow the example in volume-pv-pvc.yaml.

# Notes for the VRE-DEV cluster.
# StorageClass is not needed because is already deployed when starting the cluster.
# Othersiwe, have a look to the documentation on the link above
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: cvmfs
# provisioner: cvmfs.csi.cern.ch
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-pvc
  namespace: jhub-dev
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      # Volume size value has no effect and is ignored
      # by the driver, but must be non-zero.
      storage: 1
  storageClassName: cvmfs
---
apiVersion: v1
kind: Pod
metadata:
  name: cvmfs-client
  namespace: jhub-dev
spec:
  containers:
   - name: idle
     image: busybox
     imagePullPolicy: IfNotPresent
     command: [ "/bin/sh", "-c", "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
     volumeMounts:
       - name: cvmfs
         mountPath: /cvmfs
         # CVMFS automount volumes must be mounted with HostToContainer mount propagation.
         mountPropagation: HostToContainer
  volumes:
   - name: cvmfs
     persistentVolumeClaim:
       claimName: cvmfs-pvc
