apiVersion: v1
kind: Pod
metadata:
  name: rucio-client
  namespace: rucio-dev
spec:
  containers:
  - name: rucio-client-dev
    image: ghcr.io/vre-hub/rucio-client:sha-ae6ac2c
    imagePullPolicy: Always
    env:
    - name: RUCIO_CFG_RUCIO_HOST
      value: "https://vre-dev-rucio.cern.ch"
    - name: RUCIO_CFG_AUTH_HOST
      value: "https://vre-dev-auth-rucio.cern.ch"
    - name: RUCIO_CFG_ACCOUNT
      value: "root"
    - name: RUCIO_CFG_AUTH_TYPE
      value: "userpass"
    - name: RUCIO_CFG_USERNAME
      valueFrom:
        secretKeyRef:
          name: rucio-root-account
          key: root-username
    - name: RUCIO_CFG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rucio-root-account
          key: root-password 
    command: ["sleep","3600"]
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: rucio-noise
#   namespace: rucio-vre
# spec:
#   schedule: "*/10 * * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 1
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           restartPolicy: OnFailure 
#           containers:
#             - name: rucio-noise
#               image: ghcr.io/vre-hub/vre-rucio-noise:v1.0.0-rc0-10-be00405
#               volumeMounts:
#               - name: rucio-cfg
#                 mountPath: /opt/rucio/etc/
#               - name: prod-rucio-x509up
#                 mountPath: /tmp/
#               tty: true
#               imagePullPolicy: Always
#               command:
#               - /bin/sh
#               - -c
#               - date; ls -l /etc/pki/tls/certs/; ls -l /tmp/; cd /opt/rucio/etc/; pwd; echo Hello from rucio-noise container; 
#                 export RUCIO_CONFIG=/opt/rucio/etc/rucio.cfg; echo Exported config; cat /opt/rucio/etc/rucio.cfg; rucio -vvv whoami; 
#                 cd /home; export FSIZE=10M; FILE_SIZE=${FSIZE} /bin/bash produce_noise.sh; echo "Rucio noise cronjob ${FSIZE} Done!"
#           volumes:
#             - name: rucio-cfg
#               secret:
#                 secretName: escape-service-account
#                 defaultMode: 0400
#             - name: prod-rucio-x509up
#               secret:
#                 secretName: prod-rucio-x509up
#---
